# Copyright (C) 2021 Square, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.
name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    tags: ["v[0-9]+.[0-9]+*"]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-main:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Globals
      run: |
        echo "RELEASE_REPO=/tmp/sqldelight_release_repo" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Mount caches
      uses: actions/cache@v2
      with:
        path: |
          "/home/runner/.cache/bazel"
          "/home/runner/.m2/repository"
        key: caches-${{ runner.os }}
    - name: Setup bazelisk for Bazel builds
      uses: holvonix-open/setup-bazelisk@v0.6.1
    - name: Build Wrapper
      run: bazel build //actions/...
    - name: Test Wrapper and Rules
      run: bazel test //actions/... //:sqldelight_tests
    - name: Extract Rules Release Package (for testing)
      run: |
        bazel build //:rules_sqldelight_release
        rm -rf ${{ env.RELEASE_REPO }}
        mkdir -p ${{ env.RELEASE_REPO }}
        tar -xzvf bazel-bin/rules_sqldelight_release.tgz -C ${{ env.RELEASE_REPO }}
        ls -l ${{ env.RELEASE_REPO }}
    - name: "Test Sample: Trivial"
      run: |
        pushd samples/trivial
        bazel build --override_repository=rules_sqldelight=${{ env.RELEASE_REPO }} //...
        popd
    - name: "Test Sample: Dialect"
      run: |
        pushd samples/dialect
        bazel build --override_repository=rules_sqldelight=${{ env.RELEASE_REPO }} //...
        popd
